---
- name: Check dependencies
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: False
    update_cache: yes
    cache_valid_time: 3600
  sudo: yes
  with_items:
    - php5-gd
    - php5-mysql
    - php5-curl
    - php5-intl
    - php5-mcrypt
    - php5-imagick
    - php5-fpm
